Repository APP-iOS3rd/PJ3T3_Postie, pull requests merged in 2024-01, with the labels that each got.

#16 Firebase package 추가
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
Labels: ⚙️ Setting, 👀 Review Needed

#22 앱 사용을 위한 라벨 custom 작업
  .github/trafico.yml
Labels: ⚙️ Setting, 🔍 Ready for Review

#17 LoginView UI 구성
  PJ3T3_Postie/Core/Login/View/LoginInputView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/RegistrationView.swift
Labels: ✨ Feat, 👀 리뷰 요청, 🔍 추가 승인 필요

#20 AddLetterView UI 및 텍스트 인식 기능 구현
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/View/LetterImageFullScreenView.swift
  PJ3T3_Postie/Core/Home/View/UIImagePicker.swift
  PJ3T3_Postie/Core/Home/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/TextRecognizer.swift
  PJ3T3_Postie/Extenstions/Color.swift
Labels: ✨ Feat, 👀 리뷰 요청

#25 HomeView UI 구현
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/Contents.json
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Extenstions/Color.swift
Labels: ✨ Feat, 👀 리뷰 요청, 🔍 추가 승인 필요

#23 Email 로그인, 로그아웃 기능 구현
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/RegistrationView.swift
  PJ3T3_Postie/Core/Login/ViewModel/AuthViewModel.swift
  PJ3T3_Postie/Core/Root/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Model/User.swift
Labels: ✨ Feat, 👀 리뷰 요청

#28 앱에 로그인하여 Firestore에 데이터 추가하는 기능
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/ViewModel/FirestoreManager.swift
  PJ3T3_Postie/Core/Home/ViewModel/FirestoreViewModel.swift
  PJ3T3_Postie/Core/Login/View/RegistrationView.swift
  PJ3T3_Postie/Core/Root/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Model/Letter.swift
Labels: ✨ Feat, 📀 Data, 👀 리뷰 요청

#29 LetterDetailView UI 구현
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Home/View/LetterImageFullScreenView.swift
  PJ3T3_Postie/Core/Home/View/PageViewController.swift
  PJ3T3_Postie/Core/Home/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/LetterDetailViewModel.swift
  PJ3T3_Postie/Extenstions/String.swift
  PJ3T3_Postie/Model/Letter.swift
Labels: ✨ Feat, 👀 리뷰 요청

#41 Homeview UI 개편 및 임시 사이드메뉴, 세팅뷰 구현
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Home/ViewModel/FirestoreManager.swift
  PJ3T3_Postie/Core/Setting/View/ProfileView.swift
  PJ3T3_Postie/Extenstions/Date.swift
  PJ3T3_Postie/Font/SourceSerifPro-Black.otf
  PJ3T3_Postie/Font/SourceSerifPro-Light.otf
Labels: 🎨 Design, ✨ Feat, ⚙️ Setting, 👀 리뷰 요청

#42 Firebase Storage에 이미지 업로드 및 뷰에 Load
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/ViewModel/FirestoreManager.swift
  PJ3T3_Postie/Core/Home/ViewModel/StorageManager.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Model/Letter.swift
Labels: ✨ Feat, 📀 Data, 👀 리뷰 요청

#38 MapView 우체국API연결
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Components/Button.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapApi.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapViewModel.swift
Labels: ✨ Feat, 👀 리뷰 요청

#52 Firestore의 편지 데이터를 수정하거나 삭제할 수 있다.
  PJ3T3_Postie/Core/Home/ViewModel/FirestoreManager.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
Labels: ✨ Feat, 📀 Data, 👍 Merge 진행

#55 Storage 이미지 삭제 기능 구현 및 Letter 구조체 수정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/ViewModel/FirestoreManager.swift
  PJ3T3_Postie/Core/Home/ViewModel/StorageManager.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/RegistrationView.swift
  PJ3T3_Postie/Core/Login/ViewModel/AuthManager.swift
  PJ3T3_Postie/Core/Root/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Model/LetterPhoto.swift
Labels: ✨ Feat, 📀 Data, 🔨 Refactor, 👀 리뷰 요청, 🔍 추가 승인 필요

#59 Shop 데이터 관리를 위한 모델 생성 및 데이터 호출 코드 작성
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/ViewModel/FirestoreManager.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Model/Shop.swift
Labels: ✨ Feat, 📀 Data, 👀 리뷰 요청

#57 Feat: ShopView 추가 및 SFSafariview 추가
  PJ3T3_Postie/Core/Shop/View/ShopView.swift
Labels: 🎨 Design, ✨ Feat, 👍 Merge 진행

#47 AddLetterView 디자인 수정 및 한 줄요약 추가
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Home/View/LetterDetailView.swift
Labels: 🎨 Design, 👀 리뷰 요청

#51 Mapview NaverMap연결
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Map/View/Coordinator.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapApi.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapViewModel.swift
  PJ3T3_Postie/Core/Map/ViewModel/MyCoord.swift
  PJ3T3_Postie/Core/Map/ViewModel/NaverMap.swift
  PJ3T3_Postie/Core/Root/ContentView.swift
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
Labels: ✨ Feat, ✅ Test, 👀 리뷰 요청

#67 파일 및 폴더 정리
  PJ3T3_Postie.xcodeproj/project.pbxproj
Labels: 🚨 긴급 승인 요청, 👀 리뷰 요청, 🍖 주원, ⭐️ 운기

#68 MapView 지도연결
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Map/View/Coordinator.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapApi.swift
Labels: ✨ Feat, ✅ Test, 👀 리뷰 요청

#61 Firebase 관련 코드 리팩토링 및 Letter 구조체 업데이트
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/postieBeige.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/postieBlack.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/postieGray.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/postieLightGray.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/postieOrange.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/postieWhite.colorset/Contents.json
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Manager/AuthManager.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
  PJ3T3_Postie/Manager/StorageManager.swift
  PJ3T3_Postie/Model/Letter.swift
  PJ3T3_Postie/Model/LetterPhoto.swift
Labels: ✨ Feat, 📀 Data, ⚙️ Setting, 🔨 Refactor, 👀 리뷰 요청
