Repository APP-iOS3rd/PJ3T3_Postie, pull requests merged in 2024-02, with the labels that each got.

#65 asset 이미지 추가, 테마 그림자 가려지는 현상 및 이미지 없는 버튼 터치시 에러 발생 수정
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/crayon.png
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/스크린샷 2024-01-30 오전 10.54.00 1.png
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/스크린샷 2024-01-30 오전 10.54.00.png
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/digimon.png
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/스크린샷 2024-01-30 오전 10.51.05 1.png
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/스크린샷 2024-01-30 오전 10.51.05.png
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/kuma.png
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/스크린샷 2024-01-30 오전 10.52.44 1.png
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/스크린샷 2024-01-30 오전 10.52.44.png
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/poketmon.png
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/스크린샷 2024-01-30 오전 10.49.22 1.png
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/스크린샷 2024-01-30 오전 10.49.22.png
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/poketmon2.png
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/스크린샷 2024-01-30 오전 10.47.54 1.png
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/스크린샷 2024-01-30 오전 10.47.54.png
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/sanrio.png
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/스크린샷 2024-01-30 오전 10.50.19 1.png
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/스크린샷 2024-01-30 오전 10.50.19.png
  PJ3T3_Postie/Core/Shop/View/ShopView.swift
Labels: 📀 Data, 🛠️ Fix, 👀 리뷰 요청

#75 HomeView 최종 컬러로 변경, 그룹뷰 배열 추가 및 ThemeView 생성
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  PJ3T3_Postie/Assets.xcassets/PostieTheme_LetterGroup.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/PostieTheme_LetterGroup.imageset/PostieTheme_LetterGroup.png
  PJ3T3_Postie/Assets.xcassets/PostieTheme_LetterList.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/PostieTheme_LetterList.imageset/PostieTheme_LetterList.png
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieBlack.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieBlack.imageset/PostieTheme_PostieBlack.png
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieBlue.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieBlue.imageset/PostieTheme_PostieBlue.png
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieGreen.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieGreen.imageset/PostieTheme_PostieGreen.png
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieOrange.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieOrange.imageset/PostieTheme_PostieOrange.png
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieYellow.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/PostieTheme_PostieYellow.imageset/PostieTheme_PostieYellow.png
  PJ3T3_Postie/Assets.xcassets/Posty_Receiving.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty_Receiving.imageset/Posty_Receiving.png
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileView.swift
  PJ3T3_Postie/Core/Setting/View/ThemeView.swift
  PJ3T3_Postie/Model/Shop.swift
Labels: 🎨 Design, ✨ Feat, ⚙️ Setting, 👀 리뷰 요청

#79 MapView 초기값 내 위치값으로 설정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Map/View/CoordinaterEtc.swift
  PJ3T3_Postie/Core/Map/View/Coordinator.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/LocationManager.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapApi.swift
  PJ3T3_Postie/Core/Map/ViewModel/MyCoord.swift
  PJ3T3_Postie/Core/Map/ViewModel/NaverMap.swift
  PJ3T3_Postie/Core/Root/ContentView.swift
  Pods/Pods.xcodeproj/project.pbxproj
Labels: ✨ Feat, ✅ Test, 👍 Merge 진행

#82 HomeView 그룹 편지뷰 구현, 플로팅 버튼 버그 수정, 컬러셋 적용 및 코드 리팩토링
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/postieDarkGray.colorset/Contents.json
  PJ3T3_Postie/Core/Home/View/GroupedFavoriteListLetter.swift
  PJ3T3_Postie/Core/Home/View/GroupedLetterView.swift
  PJ3T3_Postie/Core/Home/View/GroupedListLetterView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Home/View/ListLetterView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileView.swift
  PJ3T3_Postie/Core/Setting/View/ThemeView.swift
Labels: 🐛 Bug, 🎨 Design, ✨ Feat, ⚙️ Setting, 🛠️ Fix, 🔨 Refactor, 👀 리뷰 요청

#80 Google 로그인 구현 및 AuthModel 리팩토링
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Home/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Login/View/EmailLoginView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
  PJ3T3_Postie/Core/Login/View/RegistrationView.swift
  PJ3T3_Postie/Core/Root/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Manager/AuthManager.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
  PJ3T3_Postie/Manager/GoogleSignInHelper.swift
  PJ3T3_Postie/Manager/StorageManager.swift
  PJ3T3_Postie/Model/GoogleUser.swift
  PJ3T3_Postie/Model/PostieUser.swift
  PJ3T3_Postie/Model/User.swift
Labels: ✨ Feat, 📀 Data, ⚙️ Setting, 👀 리뷰 요청, 🔍 추가 승인 필요

#89 HomeView theme 기능 작동 및 로딩뷰(SplashScreenView) 생성
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/Posty/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/Posty_Receiving.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/Posty_Receiving.imageset/Posty_Receiving.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceiving.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceiving.imageset/postyReceiving.png
  PJ3T3_Postie/Assets.xcassets/ThemeColors/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieBeige.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieBlack.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieBlue.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieDarkGray.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieGray.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieGreen.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieLightBeige.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieLightBlack.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieLightBlue.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieLightGray.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieLightYellow.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieOrange.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieRealWhite.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieSpaceGray.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieWhite.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeColors/postieYellow.colorset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_LetterGroup.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_LetterGroup.imageset/PostieTheme_LetterGroup.png
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_LetterList.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_LetterList.imageset/PostieTheme_LetterList.png
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieBlack.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieBlack.imageset/PostieTheme_PostieBlack.png
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieBlue.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieBlue.imageset/PostieTheme_PostieBlue.png
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieGreen.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieGreen.imageset/PostieTheme_PostieGreen.png
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieOrange.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieOrange.imageset/PostieTheme_PostieOrange.png
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieYellow.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/PostieTheme_PostieYellow.imageset/PostieTheme_PostieYellow.png
  PJ3T3_Postie/Core/Home/View/GroupedFavoriteListLetterView.swift
  PJ3T3_Postie/Core/Home/View/GroupedLetterView.swift
  PJ3T3_Postie/Core/Home/View/GroupedListLetterView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Home/View/ListLetterView.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Core/Root/ViewModel/ContenViewModel.swift
  PJ3T3_Postie/Core/Setting/View/ProfileView.swift
  PJ3T3_Postie/Core/Setting/View/SplashScreenView.swift
  PJ3T3_Postie/Core/Setting/View/ThemeView.swift
  PJ3T3_Postie/Core/Setting/ViewModel/SettingViewModel.swift
  PJ3T3_Postie/Extenstions/Color.swift
Labels: 🐛 Bug, ✨ Feat, ⚙️ Setting, 🔨 Refactor, 👀 리뷰 요청

#93 Apple 로그인 구현, Bundle ID 업데이트
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie.xcodeproj/xcshareddata/xcschemes/PJ3T3_Postie.xcscheme
  PJ3T3_Postie/Assets.xcassets/AppleSignIn.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/AppleSignIn.imageset/Fixed.png
  PJ3T3_Postie/Assets.xcassets/AppleSignIn.imageset/Fixed@2x.png
  PJ3T3_Postie/Assets.xcassets/AppleSignIn.imageset/Fixed@3x.png
  PJ3T3_Postie/Assets.xcassets/GoogleSignIn.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/GoogleSignIn.imageset/Fixed.png
  PJ3T3_Postie/Assets.xcassets/GoogleSignIn.imageset/Fixed@2x.png
  PJ3T3_Postie/Assets.xcassets/GoogleSignIn.imageset/Fixed@3x.png
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
  PJ3T3_Postie/Manager/AppleSignInHelper.swift
  PJ3T3_Postie/Manager/AuthManager.swift
  PJ3T3_Postie/Model/AppleUser.swift
  PJ3T3_Postie/PJ3T3_Postie.entitlements
Labels: ✨ Feat, 📀 Data, ⚙️ Setting, 👍 Merge 진행

#97 ContentView에 NicknameView가 뜨는 로직이 사라져 계정 생성이 정상적으로 이루어지지 않는 이슈 개선
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
Labels: 🛠️ Fix, 🚨 긴급 승인 요청, 👀 리뷰 요청

#101 MapView button을 통해 우체국/우체통 보여주기 구현
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Map/View/Coordinator.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapApi.swift
Labels: ✨ Feat, 👀 리뷰 요청

#102 Search뷰 검색 기능 구현, 앱 회전 및 OS 지원 설정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Home/View/SearchView.swift
  PJ3T3_Postie/Extenstions/View.swift
  PJ3T3_Postie/Manager/AppleSignInHelper.swift
  PJ3T3_Postie/Manager/AuthManager.swift
Labels: 🎨 Design, ✨ Feat, ⚙️ Setting, 👀 리뷰 요청

#107 편지 디테일 뷰 수정 기능 추가
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Home/View/PageViewController.swift
  PJ3T3_Postie/Core/Home/ViewModel/LetterDetailViewModel.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
Labels: ✨ Feat, 📀 Data, 👀 리뷰 요청

#121 Firestore에서 공지를 fetch할 수 있다
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
  PJ3T3_Postie/Manager/FirestoreNoticeManager.swift
  PJ3T3_Postie/Manager/FirestoreShopManager.swift
  PJ3T3_Postie/Model/OfficialLetter.swift
Labels: ✨ Feat, 📀 Data, 👍 Merge 진행, ⭐️ 운기

#119 회원탈퇴 기능 및 LoadingView 구현, 앱 재설치 버그 수정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Components/ClearBackground.swift
  PJ3T3_Postie/Components/LoadingView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Extenstions/EnvironmentValues.swift
  PJ3T3_Postie/Manager/AppleSignInHelper.swift
  PJ3T3_Postie/Manager/AuthCaseHelper.swift
  PJ3T3_Postie/Manager/AuthManager.swift
  PJ3T3_Postie/Manager/CryptoUtils.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
  PJ3T3_Postie/Manager/FirestoreNoticeManager.swift
  PJ3T3_Postie/Manager/FirestoreShopManager.swift
  PJ3T3_Postie/Manager/StorageManager.swift
  PJ3T3_Postie/Model/Letter.swift
  PJ3T3_Postie/Model/OfficialLetter.swift
Labels: 🎨 Design, ✨ Feat, 📀 Data, 🛠️ Fix, 👀 리뷰 요청

#136 Firestore 디버깅, 닉네임뷰와 로그인뷰 UI 업데이트 및 테마 대응
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Components/LoadingView.swift
  PJ3T3_Postie/Core/Home/View/SearchView.swift
  PJ3T3_Postie/Core/Login/View/DeleteAccountButtonView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
Labels: 🎨 Design, ✨ Feat, 🛠️ Fix, 👀 리뷰 요청, 🔍 추가 승인 필요, 🐼 지원

#143 편지 저장 및 수정 로직 변경에 따른 firestore, storage 코드 재구현
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
  PJ3T3_Postie/Manager/StorageManager.swift
  PJ3T3_Postie/Model/Letter.swift
Labels: ✨ Feat, 📀 Data, ⚙️ Setting, 👀 리뷰 요청

#148 편지 수정, 추가, 삭제 리팩토링
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/View/EditLetterView.swift
  PJ3T3_Postie/Core/Home/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Home/View/LetterImageFullScreenView.swift
  PJ3T3_Postie/Core/Home/View/PageViewController.swift
  PJ3T3_Postie/Core/Home/View/UIImagePicker.swift
  PJ3T3_Postie/Core/Home/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/LetterDetailViewModel.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
  PJ3T3_Postie/Manager/StorageManager.swift
Labels: ✨ Feat, 🔨 Refactor, 👍 Merge 진행, 🔮 은수

#131 MapView 우체국 정보 넣기. 현 지도 검색 버튼 위치 수정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Map/View/Coordinator.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapViewModel.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
Labels: ✨ Feat, 👀 리뷰 요청

#150 프로젝트 파일 내의 일부 파일 중복 및 ContentView 중복 init 수정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Root/View/ContentView.swift
Labels: ⚙️ Setting, 🛠️ Fix, 🚨 긴급 승인 요청, 👍 Merge 진행

#152 느린 우체통을 위한 Local Push 설정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Manager/NotificationManager.swift
Labels: ✨ Feat, ⚙️ Setting, 👀 리뷰 요청, 🎄 현진

#160 편지 AI 요약 기능 연결, 글자 인식 리팩토링 및 버그 해결
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/View/EditLetterView.swift
  PJ3T3_Postie/Core/Home/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Home/View/UIImagePicker.swift
  PJ3T3_Postie/Core/Home/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/TextRecognizer.swift
Labels: 🐛 Bug, ✨ Feat, 🔨 Refactor, 👍 Merge 진행, 🐼 지원

#151 멋사 계정 -> 개인 계정 전환을 위한 설정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/PJ3T3_Postie.entitlements
Labels: ⚙️ Setting, 👀 리뷰 요청

#161 닉네임뷰 버그 해결 및 회원가입, 탈퇴 오류 에러 핸들링
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Login/View/DeleteAccountButtonView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
  PJ3T3_Postie/Core/Login/View/ReAuthButtonView.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Manager/AppleSignInHelper.swift
  PJ3T3_Postie/Manager/AuthCaseHelper.swift
  PJ3T3_Postie/Manager/AuthManager.swift
Labels: 🐛 Bug, ✨ Feat, 👍 Merge 진행, 🍖 주원

#166 Map view 기능 및 UI수정
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Map/View/Coordinator.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/LocationManager.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapApi.swift
Labels: ✨ Feat, 🛠️ Fix, 🔨 Refactor, 👀 리뷰 요청, 🎄 현진

#174 로그인 뷰 작은 화면 대응, 강제 업데이트 추가 및 로그인 관련 디버깅
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Login/View/DeleteAccountButtonView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/FirebaseTestRowView.swift
  PJ3T3_Postie/Core/Setting/View/FirebaseTestView.swift
  PJ3T3_Postie/Manager/AppStoreUpdateChecker.swift
  PJ3T3_Postie/Manager/AppleSignInHelper.swift
  PJ3T3_Postie/Manager/AuthCaseHelper.swift
  PJ3T3_Postie/Manager/AuthManager.swift
Labels: 🎨 Design, ✨ Feat, 👀 리뷰 요청, 🍖 주원, 🎄 현진

#164 느린 우체통 뷰 생성 및 알림 기능 연결
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Home/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Home/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Home/ViewModel/SlowPostBoxViewModel.swift
Labels: 🎨 Design, ✨ Feat, 👍 Merge 진행

#178 HomeView 나의 느린 우체통 대응
  PJ3T3_Postie/Assets.xcassets/postySketchWhite/postyThinkingSketchWhite.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/postySketchWhite/postyThinkingSketchWhite.imageset/postyThinkingSketchWhite.png
  PJ3T3_Postie/Core/Home/View/GroupedLetterView.swift
  PJ3T3_Postie/Core/Home/View/GroupedListLetterView.swift
  PJ3T3_Postie/Core/Home/View/GroupedMyListLetterView.swift
  PJ3T3_Postie/Core/Home/View/ListLetterView.swift
  PJ3T3_Postie/Core/Setting/View/NoticeView.swift
Labels: 🎨 Design, ✨ Feat, 👍 Merge 진행, 🍖 주원, 🔮 은수

#113 Feat: 테마 버튼 수정 및 이미지 비동기 구현
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/crayon.png
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/스크린샷 2024-01-30 오전 10.54.00 1.png
  PJ3T3_Postie/Assets.xcassets/crayon.imageset/스크린샷 2024-01-30 오전 10.54.00.png
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/digimon.png
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/스크린샷 2024-01-30 오전 10.51.05 1.png
  PJ3T3_Postie/Assets.xcassets/digimon.imageset/스크린샷 2024-01-30 오전 10.51.05.png
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/kuma.png
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/스크린샷 2024-01-30 오전 10.52.44 1.png
  PJ3T3_Postie/Assets.xcassets/kuma.imageset/스크린샷 2024-01-30 오전 10.52.44.png
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/poketmon.png
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/스크린샷 2024-01-30 오전 10.49.22 1.png
  PJ3T3_Postie/Assets.xcassets/poketmon.imageset/스크린샷 2024-01-30 오전 10.49.22.png
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/poketmon2.png
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/스크린샷 2024-01-30 오전 10.47.54 1.png
  PJ3T3_Postie/Assets.xcassets/poketmon2.imageset/스크린샷 2024-01-30 오전 10.47.54.png
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/sanrio.png
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/스크린샷 2024-01-30 오전 10.50.19 1.png
  PJ3T3_Postie/Assets.xcassets/sanrio.imageset/스크린샷 2024-01-30 오전 10.50.19.png
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Core/Shop/View/ShopView.swift
  PJ3T3_Postie/Core/Shop/ViewModel/ShopViewModel.swift
Labels: 🎨 Design, ✨ Feat, 👀 리뷰 요청

#180 Design: 이미지내에 text 수정
  PJ3T3_Postie/Core/Shop/View/ShopView.swift
Labels: 🎨 Design, 👍 Merge 진행, 🐼 지원

#181 SettingView 몇몇 수정
  PJ3T3_Postie/Assets.xcassets/Posty/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyHeart.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyHeart.imageset/제목_없는_아트워크 7.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyNotGood.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyNotGood.imageset/제목_없는_아트워크 11.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyQuestion.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyQuestion.imageset/제목_없는_아트워크 15.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceiving.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceiving.imageset/Posty_Receiving.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceivingBeige.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceivingBeige.imageset/postyReceiving.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceivingOrange.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyReceivingOrange.imageset/postyReceivingOrange.png
  PJ3T3_Postie/Assets.xcassets/Posty/postySending.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postySending.imageset/제목_없는_아트워크 8.png
  PJ3T3_Postie/Assets.xcassets/Posty/postySmile.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postySmile.imageset/제목_없는_아트워크 5.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyThinking.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyThinking.imageset/제목_없는_아트워크 6.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyTrumpet.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyTrumpet.imageset/제목_없는_아트워크 13.png
  PJ3T3_Postie/Assets.xcassets/Posty/postyWink.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/Posty/postyWink.imageset/제목_없는_아트워크 10.png
  PJ3T3_Postie/Components/LoadingView.swift
  PJ3T3_Postie/Core/Home/View/GroupedFavoriteListLetterView.swift
  PJ3T3_Postie/Core/Home/View/GroupedLetterView.swift
  PJ3T3_Postie/Core/Home/View/GroupedMyListLetterView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
  PJ3T3_Postie/Core/Setting/View/InformationView.swift
  PJ3T3_Postie/Core/Setting/View/NoticeView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileView.swift
  PJ3T3_Postie/Core/Setting/View/QuestionView.swift
  PJ3T3_Postie/Core/Setting/View/SplashScreenView.swift
  PJ3T3_Postie/Core/Setting/View/ThemeView.swift
  PJ3T3_Postie/Core/Setting/ViewModel/SettingViewModel.swift
Labels: 🎨 Design, ✨ Feat, 👍 Merge 진행

#183 뷰 수정 및 Logger 익스텐션 추가
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/View/EditLetterView.swift
  PJ3T3_Postie/Core/Home/View/LetterImageFullScreenView.swift
  PJ3T3_Postie/Core/Home/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Home/View/UIImagePicker.swift
  PJ3T3_Postie/Core/Home/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/LetterDetailViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/SlowPostBoxViewModel.swift
  PJ3T3_Postie/Core/Home/ViewModel/SummaryApi.swift
  PJ3T3_Postie/Core/Login/View/DeleteAccountButtonView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/ReAuthButtonView.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Map/ViewModel/LocationManager.swift
  PJ3T3_Postie/Core/Map/ViewModel/MapApi.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Extenstions/Logger.swift
  PJ3T3_Postie/Manager/AppStoreUpdateChecker.swift
  PJ3T3_Postie/Manager/AppleSignInHelper.swift
  PJ3T3_Postie/Manager/AuthManager.swift
Labels: 🎨 Design, 👀 리뷰 요청

#187 개인정보 처리방침과 이용약관을 웹뷰로 작성
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Setting/View/InformationView.swift
  PJ3T3_Postie/Core/Setting/View/InformationWebView.swift
Labels: ✨ Feat, 👍 Merge 진행, ⭐️ 운기

#188 Fix: 코드 수정
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Setting/View/SplashScreenView.swift
Labels: 👍 Merge 진행

#189 Fix/details
  PJ3T3_Postie/Core/Home/View/AddLetterView.swift
  PJ3T3_Postie/Core/Home/ViewModel/SlowPostBoxViewModel.swift
  PJ3T3_Postie/Core/Map/View/Coordinator.swift
  PJ3T3_Postie/Core/Setting/View/FirebaseTestView.swift
  PJ3T3_Postie/Core/Shop/ViewModel/ShopViewModel.swift
  PJ3T3_Postie/Manager/FirestoreManager.swift
  PJ3T3_Postie/Manager/FirestoreNoticeManager.swift
  PJ3T3_Postie/Manager/FirestoreShopManager.swift
  PJ3T3_Postie/Manager/NotificationManager.swift
  PJ3T3_Postie/Manager/StorageManager.swift
Labels: 🛠️ Fix, 👍 Merge 진행, 🐼 지원, 🔮 은수

#192 배포 이후 발견된 버그 수정(로그인버튼, 닉네임뷰, 검색필터)
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/GoogleSignInKor.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/GoogleSignInKor.imageset/GoogleSignInKor.png
  PJ3T3_Postie/Assets.xcassets/GoogleSignInKor.imageset/GoogleSignInKor@2x.png
  PJ3T3_Postie/Assets.xcassets/GoogleSignInKor.imageset/GoogleSignInKor@3x.png
  PJ3T3_Postie/Core/Home/View/SearchView.swift
  PJ3T3_Postie/Core/Login/View/LoginView.swift
  PJ3T3_Postie/Core/Login/View/NicknameView.swift
Labels: 🎨 Design, ✨ Feat, 🛠️ Fix, 👍 Merge 진행, 🍖 주원

#190 Fix 오류 수정
  PJ3T3_Postie/Assets.xcassets/ThemeImages/postieGroupBlack.imageset/Contents.json
  PJ3T3_Postie/Assets.xcassets/ThemeImages/postieGroupBlack.imageset/IMG_498B6BB49FE7-1.jpeg
  PJ3T3_Postie/Assets.xcassets/ThemeImages/postieGroupBlack.imageset/postieGroupBlack.png
  PJ3T3_Postie/Core/Home/View/GroupedMyListLetterView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Home/View/ListLetterView.swift
  PJ3T3_Postie/Core/Home/View/SearchView.swift
  PJ3T3_Postie/Core/Setting/View/AlertView.swift
  PJ3T3_Postie/Core/Setting/View/InformationView.swift
  PJ3T3_Postie/Core/Setting/View/NoticeView.swift
  PJ3T3_Postie/Core/Setting/View/QuestionView.swift
  PJ3T3_Postie/Core/Setting/View/ThemeView.swift
  PJ3T3_Postie/Extenstions/Date.swift
Labels: 🎨 Design, 🛠️ Fix, 🔨 Refactor, 👍 Merge 진행, 🍖 주원

#194 Fix:권한요청메시지...
  PJ3T3_Postie.xcodeproj/project.pbxproj
Labels: 👍 Merge 진행
